apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mysql.yaml
  - wordpress.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: mysql-pass
    literals:
      - password=test

configMapGenerator:
  - name: wordpress-config
    literals:
      - WORDPRESS_DB_HOST=wordpress-mysql
      